apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-todo-api
  labels:
    app: go-todo-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-todo-api
  template:
    metadata:
      labels:
        app: go-todo-api
    spec:
      containers:
      - name: go-todo-api
        image: go-todo-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: go-todo-api-service
  labels:
    app: go-todo-api
spec:
  type: NodePort
  selector:
    app: go-todo-api
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
